### PR TITLE
Search bar UX/UI improvements

### LINKED ISSUE #32: Improve search bar & filtering UI
# Description
There are some inconsistencies and awkward spacing in the search bar and filter's UI. There are some screenshots below of the bugs I'd fix, but I'd also recommend making some improvements in accessibility. The color contrast is pretty low and the keyboard navigation isn't great. If it's alright, I'd love to work on a solution for these improvements.

# Screenshots
Full search bar with visual overflow
Clip of search bar with text cut off
Selected filter dropdown with longer names that break the flow of the layout

# Suggested updates
- [x] Move filters beneath search bar for a more predictable layout and space for a longer search string
- [x] Fix filter list layout (i.e. give the popup list more horizontal space)
- [x] Use brand colors to provide more color contrast for accessibility
- [x] Provide visual feedback for keyboard navigation
- [x] Provide some kind of indication that a filter has been selected
- [x] Add a "quick clear" button

If approved, I'd love to be assigned this issue.

### PR DESCRIPTION
**Pull request by jessiejalca**
**Resolves #32**

# Summary
I revamped the UX/UI of the search bar, stretching the search input across the entirety of the container with the filters listed below it. The filters now use the purple brand color for highlighting and visual feedback, including highlighting a dropdown menu that has selected filters. Below the search bar is now the full list of the selected filters, where the user can quickly unselect any or clear all filters. 

It's also much easier to tab across dropdowns. The focus will skip over dropdown menus unless they're open, and each selected filter underneath is fully tabbable.

# Screenshots
Screenshot 2024-10-24 at 10 10 19 AM
Screenshot 2024-10-24 at 10 06 25 AM
Screenshot 2024-10-24 at 10 04 05 AM
Screenshot 2024-10-24 at 10 11 06 AM

### CODE REVIEW

**Review by swve — CHANGES_REQUESTED** [review]
Hey @jessiejalca, this looks awesome! It's much easier now to keep track of selected filters—definitely a big UX improvement! 

Also thanks for updating the wrong naming occurrences, I experimented quite a bit with the filter names but forgot to update the internal references.

I just have one minor suggestion : 

- The transitions on the filter buttons are a bit abrupt I think we can add `transition-all ease-linear duration-300` so that it looks more smooth. 

I appreciate the quality of the code and the organization of your commits, and I took a look at the descriptions as well. If you could group some of these commits together, that would be great! If not, no worries—I can squash them and merge. Thanks!

**Comment by jessiejalca** [comment]
@swve Thanks! Sure, I'll add the transition now. As for grouping, is there another way to group them besides squashing? I'm not sure how to do that, but I'm down to look it up and learn if you can point me in the right direction.

**Comment by swve** [comment]
@jessiejalca You can group commits using squash—it’s really handy! Here’s a quick video that explains the process: [link](https://youtu.be/V5KrD7CmO4o?feature=shared). 

For our situation, you’ll want to use "pick" on certain commits to form groups, rathr than combining everything into a single commit.
```
pick <commit-hash-1> Commit message 1
squash <commit-hash-2> Commit message 2
squash <commit-hash-3> Commit message 3
pick <commit-hash-4> Commit message 4
squash <commit-hash-5> Commit message 5
squash <commit-hash-6> Commit message 6
squash <commit-hash-7> Commit message 7
```
This way, you’ll create multiple grouped commits, rather than merging everything into just one.

I’d recommend duplicating this branch in your local Git setup and practicing the squash process there so you can get comfortable with it. This way, you can experiment freely without affecting this branch.

**Comment by jessiejalca** [comment]
@swve Hey! I added the transitions, improvement the selected filter chips, and made the selections persistent. I also squashed a few of those commits, but I didn't realize I missed some of the older ones until after pushing everything.

**Comment by swve** [comment]
Hey @jessiejalca, it looks like the commits in your PR aren’t grouped together, and some commits from the main branch were included by mistake.

No worries—everything's fixable! Git has a reflog (a history of all git actions) that you can use to return to a previous state and restart your rebase. Just curious, did you bring in those commits from main because of conflicts, or was there another reason?

If you’d like some help, we can set up a meeting to go over it together, it shouldn't take long.

**Comment by swve** [comment]
No need for additional grouping, I'll be squashing this and merging that'll be simpler

**Comment by swve** [comment]
Thanks for your contribution @jessiejalca, it's really great!

**Comment by jessiejalca** [comment]
@swve Oh ok, sorry for the complication and the late reply – I've been pretty busy of late. Glad I was able to contribute still!

**Pull request merged**
